const getExampleCharacter = () => {
  return ({
    id: "123456789",
    name: "Zathror Wilke",
    class_level: "Warlock 1",
    background: "Gladiator",
    player_name: "Ryan",
    race: "Aasimar",
    alignment: "chaotic good",
    xp: 100,
    inspiration: 1,
    proficiency_bonus: 2,
    ac: 15,
    armor_desc: "natural armor",
    max_hp: 243,
    death_success_1: true,
    death_success_2: true,
    death_success_3: false,
    death_fail_1: true,
    death_fail_2: true,
    death_fail_3: false,
    current_hp: 120,
    total_hd: "18d12+126",
    current_hd: 12,
    temp_hp: 10,
    speed: "30ft",
    strength_score: 10,
    dexterity_score: 12,
    constitution_score: 9,
    intelligence_score: 17,
    wisdom_score: 13,
    charisma_score: 21,
    strength_save_mod: 0,
    dexterity_save_mod: 2,
    constitution_save_mod: 6,
    intelligence_save_mod: 1,
    wisdom_save_mod: 2,
    charisma_save_mod: 11,
    strength_save_prof: false,
    dexterity_save_prof: true,
    constitution_save_prof: false,
    intelligence_save_prof: true,
    wisdom_save_prof: false,
    charisma_save_prof: true,
    passive_perception: 12,
    passive_investigation: 13,
    passive_insight: 9,
    acrobatics_prof: true,
    animal_handling_prof: false,
    arcana_prof: true,
    athletics_prof: false,
    deception_prof: true,
    history_prof: false,
    insight_prof: true,
    intimidation_prof: false,
    investigation_prof: true,
    medicine_prof: false,
    nature_prof: true,
    perception_prof: false,
    performance_prof: true,
    persuasion_prof: false,
    religion_prof: true,
    sleight_of_hand_prof: false,
    stealth_prof: true,
    survival_prof: false,
    acrobatics_mod: 0,
    animal_handling_mod: 1,
    arcana_mod: 2,
    athletics_mod: 3,
    deception_mod: 4,
    history_mod: 5,
    insight_mod: 6,
    intimidation_mod: 7,
    investigation_mod: 8,
    medicine_mod: 9,
    nature_mod: 10,
    perception_mod: 11,
    performance_mod: 12,
    persuasion_mod: 13,
    religion_mod: 14,
    sleight_of_hand_mod: 15,
    stealth_mod: 16,
    survival_mod: 17,
    initiative: 0,
    defenses: "Resistant to radiant and necrotic",
    senses: "blindsight 60 ft., darkvision 120 ft.",
    save_notes: "Advantage on wisdom saves",
    movement: "Fly 60 ft.",
    other_profs: "Land Vehicles\n Celestial",
    attacks: [
      {
        name: "Gun",
        notes: "Rooty Tooty Point and Shooty",
        attack_bonus: 13,
        damage_dice: "2d10+8 bludgeoning",
      },
      {
        name: "Sword",
        notes: "",
        attack_bonus: 13,
        damage_dice: "1d10+4 piercing",
      }
    ],
    attack_notes: "My attack notes",
    spell_slots_1: 1,
    spell_slots_2: 2,
    spell_slots_3: 3,
    spell_slots_4: 4,
    spell_slots_5: 5,
    spell_slots_6: 6,
    spell_slots_7: 7,
    spell_slots_8: 8,
    spell_slots_9: 9,
    spell_slots_max_1: 1,
    spell_slots_max_2: 2,
    spell_slots_max_3: 3,
    spell_slots_max_4: 4,
    spell_slots_max_5: 5,
    spell_slots_max_6: 6,
    spell_slots_max_7: 7,
    spell_slots_max_8: 8,
    spell_slots_max_9: 9,
    pact_level: 10,
    pact_available: 2,
    pact_maximum: 3,
    spells: [{
      prepared: true,
      name: "Chill Touch",
      level: 0,
      source: "Warlock",
      attack_save: "+9",
      cast_time: "1 action",
      range_shape: "120 feet",
      duration: "instantaneous",
      components: "V, S",
      notes: "You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can’t regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn. This spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8)."
    },
      {
        prepared: false,
        name: "Alarm",
        level: 1,
        source: "Warlock",
        attack_save: "",
        cast_time: "1 minute",
        range_shape: "30 feet",
        duration: "8 hours",
        components: "V,S,M(a tiny bell and a piece of fine silver wire)",
        notes: "You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is mental or audible.\n" +
          "\n" +
          "A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping.\n" +
          "\n" +
          "An audible alarm produces the sound of a hand bell for 10 seconds within 60 feet."
      }
    ],
    spells_notes: "Zathror is the greatest spellcaster in the world.",
    weight_carried: 12,
    weight_capacity: 13,
    encumberance_notes: "Encumberance Notes here",
    pp: 1,
    gp: 2,
    ep: 3,
    sp: 4,
    cp: 12,
    attuned_magic_items: [
      "Staff of Frost",
      "Pearl of Power",
      "Hat of disguise"
    ],
    attunement_notes: "I don't have any attunement notes",
    inventory: [
      {
        equipped: true,
        name: "Longsword",
        count: 1,
        weight: 10,
        value: "10 gp",
        notes: "the best sword"
      },
      {
        equipped: false,
        name: "Arrows",
        count: 10,
        weight: .5,
        value: "1 cp",
        notes: ""
      }
    ],
    inventory_notes: "Inventory isn't a concern",
    features_left: "Features 1",
    features_center: "Features 2",
    features_right: "Features 3",
    gender: "male",
    age: "Old",
    height: "6'2\"",
    weight: "10 lbs",
    faith: "Heretic",
    skin: "pale",
    eyes: "brown",
    hair: "black",
    organizations: "Wings of hope",
    backstory: "Unknown",
    personality: "the best dude",
    ideals: "Freedom",
    bonds: "His friends",
    flaws: "Absolutely none",
    notes_left: "Notes 1",
    notes_center: "Notes 2",
    notes_right: "Notes 3"
  })
}

export {getExampleCharacter}